from __future__ import annotations

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")

    google_api_key: str | None = Field(default=None, alias="GOOGLE_API_KEY")
    google_genai_use_vertexai: bool = Field(default=False, alias="GOOGLE_GENAI_USE_VERTEXAI")
    google_cloud_project: str | None = Field(default=None, alias="GOOGLE_CLOUD_PROJECT")
    google_cloud_location: str = Field(default="us-central1", alias="GOOGLE_CLOUD_LOCATION")
    live_model: str = Field(default="gemini-3.1-flash-live-preview", alias="LIVE_MODEL")
    live_system_instruction: str | None = Field(default=None, alias="LIVE_SYSTEM_INSTRUCTION")
    live_response_modalities: str | None = Field(default=None, alias="LIVE_RESPONSE_MODALITIES")
    gemini_simple_assistant_mode: bool = Field(default=False, alias="GEMINI_SIMPLE_ASSISTANT_MODE")
    gemini_command_model: str = Field(default="gemini-2.5-flash", alias="GEMINI_COMMAND_MODEL")
    chrome_listener_host: str = Field(default="127.0.0.1", alias="CHROME_LISTENER_HOST")
    chrome_listener_port: int = Field(default=8765, alias="CHROME_LISTENER_PORT")
    chrome_auto_open: bool = Field(default=True, alias="CHROME_AUTO_OPEN")
    gemini_speak_replies: bool = Field(default=True, alias="GEMINI_SPEAK_REPLIES")
    gemini_voice_assistant_mode: bool = Field(default=False, alias="GEMINI_VOICE_ASSISTANT_MODE")
    gemini_require_wake_word: bool = Field(default=True, alias="GEMINI_REQUIRE_WAKE_WORD")
    gemini_voice_wake_word: str = Field(default="gemini", alias="GEMINI_VOICE_WAKE_WORD")
    gemini_wake_window_seconds: float = Field(default=8.0, alias="GEMINI_WAKE_WINDOW_SECONDS")
    gemini_bootstrap_user_text: str | None = Field(default=None, alias="GEMINI_BOOTSTRAP_USER_TEXT")
    gemini_keepalive_seconds: int = Field(default=0, alias="GEMINI_KEEPALIVE_SECONDS")
    gemini_keepalive_text: str = Field(default="status", alias="GEMINI_KEEPALIVE_TEXT")
    gemini_auto_reconnect: bool = Field(default=True, alias="GEMINI_AUTO_RECONNECT")
    gemini_reconnect_backoff_seconds: float = Field(default=2.0, alias="GEMINI_RECONNECT_BACKOFF_SECONDS")
    gemini_max_reconnect_backoff_seconds: float = Field(default=30.0, alias="GEMINI_MAX_RECONNECT_BACKOFF_SECONDS")
    gemini_audio_enabled: bool = Field(default=True, alias="GEMINI_AUDIO_ENABLED")
    gemini_video_enabled: bool = Field(default=False, alias="GEMINI_VIDEO_ENABLED")
    gemini_audio_sample_rate_hz: int = Field(default=16000, alias="GEMINI_AUDIO_SAMPLE_RATE_HZ")
    gemini_audio_blocksize_frames: int = Field(default=1024, alias="GEMINI_AUDIO_BLOCKSIZE_FRAMES")
    gemini_audio_input_device: str | None = Field(default=None, alias="GEMINI_AUDIO_INPUT_DEVICE")
    gemini_audio_output_enabled: bool = Field(default=True, alias="GEMINI_AUDIO_OUTPUT_ENABLED")
    gemini_audio_output_device: str | None = Field(default=None, alias="GEMINI_AUDIO_OUTPUT_DEVICE")
    gemini_video_device_index: int = Field(default=0, alias="GEMINI_VIDEO_DEVICE_INDEX")
    gemini_video_source_mode: str = Field(default="obs_program_scene", alias="GEMINI_VIDEO_SOURCE_MODE")
    gemini_video_source_name: str | None = Field(default=None, alias="GEMINI_VIDEO_SOURCE_NAME")
    gemini_video_fps: float = Field(default=2.0, alias="GEMINI_VIDEO_FPS")
    gemini_video_width: int = Field(default=1280, alias="GEMINI_VIDEO_WIDTH")
    gemini_video_height: int = Field(default=720, alias="GEMINI_VIDEO_HEIGHT")
    gemini_video_jpeg_quality: int = Field(default=70, alias="GEMINI_VIDEO_JPEG_QUALITY")

    enable_vlm: bool = Field(default=False, alias="ENABLE_VLM")
    vlm_model: str = Field(default="nvidia/nemotron-nano-12b-v2-vl", alias="VLM_MODEL")
    vlm_base_url: str = Field(default="https://integrate.api.nvidia.com", alias="VLM_BASE_URL")
    nvidia_api_key: str | None = Field(default=None, alias="NVIDIA_API_KEY")
    vlm_poll_seconds: float = Field(default=1.0, alias="VLM_POLL_SECONDS")
    vlm_request_timeout_seconds: float = Field(default=12.0, alias="VLM_REQUEST_TIMEOUT_SECONDS")
    vlm_max_actions_per_turn: int = Field(default=2, alias="VLM_MAX_ACTIONS_PER_TURN")
    vlm_allowed_tools: str | None = Field(default="switch_scene", alias="VLM_ALLOWED_TOOLS")
    vlm_action_cooldown_seconds: float = Field(default=5.0, alias="VLM_ACTION_COOLDOWN_SECONDS")
    vlm_scene_switch_delay_seconds: float = Field(default=1.5, alias="VLM_SCENE_SWITCH_DELAY_SECONDS")
    vlm_error_backoff_base_seconds: float = Field(default=1.0, alias="VLM_ERROR_BACKOFF_BASE_SECONDS")
    vlm_error_backoff_max_seconds: float = Field(default=8.0, alias="VLM_ERROR_BACKOFF_MAX_SECONDS")
    vlm_system_instruction: str | None = Field(default=None, alias="VLM_SYSTEM_INSTRUCTION")
    vlm_role: str = Field(default="director", alias="VLM_ROLE")
    vlm_enable_tool_calls: bool = Field(default=False, alias="VLM_ENABLE_TOOL_CALLS")
    vlm_kill_detection_enabled: bool = Field(default=True, alias="VLM_KILL_DETECTION_ENABLED")
    vlm_kill_keywords: str = Field(default="eliminated,knocked,kill,frag,headshot", alias="VLM_KILL_KEYWORDS")

    obs_host: str = Field(default="127.0.0.1", alias="OBS_HOST")
    obs_port: int = Field(default=4455, alias="OBS_PORT")
    obs_password: str = Field(default="", alias="OBS_PASSWORD")
    scene_gameplay_focus: str = Field(default="Gameplay_Focus", alias="SCENE_GAMEPLAY_FOCUS")
    scene_chatting_focus: str = Field(default="Chatting_Focus", alias="SCENE_CHATTING_FOCUS")
    input_host_mic: str = Field(default="Host Mic", alias="INPUT_HOST_MIC")
    source_sfx_airhorn: str = Field(default="SFX_Airhorn", alias="SOURCE_SFX_AIRHORN")
    source_lower_third_text: str = Field(default="LowerThirdText", alias="SOURCE_LOWER_THIRD_TEXT")
    source_host_prompt_text: str = Field(default="HostPromptText", alias="SOURCE_HOST_PROMPT_TEXT")
    source_chat_question_text: str = Field(default="ChatQuestionText", alias="SOURCE_CHAT_QUESTION_TEXT")
    source_broll_image: str = Field(default="BrollImage", alias="SOURCE_BROLL_IMAGE")

    segment_max_minutes: int = Field(default=20, alias="SEGMENT_MAX_MINUTES")
    chat_batch_seconds: int = Field(default=60, alias="CHAT_BATCH_SECONDS")
    run_simulation_loops_with_gemini: bool = Field(default=False, alias="RUN_SIMULATION_LOOPS_WITH_GEMINI")
    ai_only_scene_switching: bool = Field(default=True, alias="AI_ONLY_SCENE_SWITCHING")
    gemini_scene_switch_delay_seconds: float = Field(default=3.0, alias="GEMINI_SCENE_SWITCH_DELAY_SECONDS")
    scene_min_dwell_seconds: float = Field(default=3.0, alias="SCENE_MIN_DWELL_SECONDS")
    cough_recovery_seconds: float = Field(default=1.0, alias="COUGH_RECOVERY_SECONDS")
    runtime_status_log_seconds: int = Field(default=15, alias="RUNTIME_STATUS_LOG_SECONDS")
    gemini_receive_idle_log_seconds: int = Field(default=15, alias="GEMINI_RECEIVE_IDLE_LOG_SECONDS")
    gemini_use_vlm_context: bool = Field(default=True, alias="GEMINI_USE_VLM_CONTEXT")
    gemini_vlm_context_min_interval_seconds: float = Field(default=2.0, alias="GEMINI_VLM_CONTEXT_MIN_INTERVAL_SECONDS")
    gemini_chat_actions_only_in_chat_scene: bool = Field(default=True, alias="GEMINI_CHAT_ACTIONS_ONLY_IN_CHAT_SCENE")
    host_username: str = Field(default="Tanish", alias="HOST_USERNAME")
    enable_gemini: bool = Field(default=False, alias="ENABLE_GEMINI")


settings = Settings()
